version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node@4.7
    steps:
      - checkout
      - run:
         name: Install npm dependecies
         command: |
           npm install --save
      - run:
          name: Run unit tests
          command: |
            npm test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  build_tests:
    jobs:
      - run_tests
      